"""Mock screening databases, country risk indexes, and demo onboarding scenarios for KYC Maker Agent."""

from typing import List, Dict, Any

COUNTRY_RISK_INDEX: Dict[str, Dict[str, Any]] = {
    "US": {"name": "United States", "risk_level": "LOW", "score": 12, "fatf_status": "COMPLIANT"},
    "GB": {"name": "United Kingdom", "risk_level": "LOW", "score": 14, "fatf_status": "COMPLIANT"},
    "DE": {"name": "Germany", "risk_level": "LOW", "score": 11, "fatf_status": "COMPLIANT"},
    "DK": {"name": "Denmark", "risk_level": "LOW", "score": 8, "fatf_status": "COMPLIANT"},
    "SG": {"name": "Singapore", "risk_level": "LOW", "score": 10, "fatf_status": "COMPLIANT"},
    "CH": {"name": "Switzerland", "risk_level": "LOW", "score": 11, "fatf_status": "COMPLIANT"},
    "FR": {"name": "France", "risk_level": "LOW", "score": 13, "fatf_status": "COMPLIANT"},
    "CA": {"name": "Canada", "risk_level": "LOW", "score": 12, "fatf_status": "COMPLIANT"},
    "LU": {"name": "Luxembourg", "risk_level": "LOW", "score": 12, "fatf_status": "COMPLIANT"},
    "NL": {"name": "Netherlands", "risk_level": "LOW", "score": 12, "fatf_status": "COMPLIANT"},
    "AE": {"name": "United Arab Emirates", "risk_level": "MEDIUM", "score": 45, "fatf_status": "INCREASED_MONITORING"},
    "CY": {"name": "Cyprus", "risk_level": "MEDIUM", "score": 48, "fatf_status": "COMPLIANT"},
    "CO": {"name": "Colombia", "risk_level": "MEDIUM", "score": 52, "fatf_status": "COMPLIANT"},
    "PA": {"name": "Panama", "risk_level": "HIGH", "score": 72, "fatf_status": "INCREASED_MONITORING"},
    "KY": {"name": "Cayman Islands", "risk_level": "MEDIUM", "score": 42, "fatf_status": "COMPLIANT"},
    "RU": {"name": "Russian Federation", "risk_level": "HIGH", "score": 88, "fatf_status": "SANCTIONS_REGIME"},
    "IR": {"name": "Iran", "risk_level": "CRITICAL", "score": 98, "fatf_status": "FATF_BLACK_LIST"},
    "KP": {"name": "North Korea (DPRK)", "risk_level": "CRITICAL", "score": 100, "fatf_status": "FATF_BLACK_LIST"},
    "MM": {"name": "Myanmar", "risk_level": "CRITICAL", "score": 92, "fatf_status": "FATF_BLACK_LIST"},
    "SY": {"name": "Syrian Arab Republic", "risk_level": "CRITICAL", "score": 96, "fatf_status": "FATF_BLACK_LIST"},
}

SANCTIONS_WATCHLIST: List[Dict[str, Any]] = [
    {
        "id": "SANC-001",
        "entity_name": "Tariq Al-Mansoor",
        "aliases": ["Tarek Al-Mansur", "Tariq Mansoor", "Abu Tariq"],
        "list_name": "OFAC SDN (Specially Designated Nationals)",
        "program": "SDGT (Global Terrorism & Illicit Finance Network)",
        "country": "SY",
        "dob": "1974-05-18",
        "remarks": "Facilitator of illicit fund transfers across sanctioned jurisdictions and front companies.",
    },
    {
        "id": "SANC-002",
        "entity_name": "Viktor Kozlov",
        "aliases": ["Victor Kozlov", "V. A. Kozlov"],
        "list_name": "EU Consolidated Sanctions List & UK OFSI",
        "program": "RUSSIA-EO14024 (Annex I)",
        "country": "RU",
        "dob": "1968-11-03",
        "remarks": "Major shareholder in sanctioned state-affiliated defense procurement conglomerates.",
    },
    {
        "id": "SANC-003",
        "entity_name": "Horizon Shipping Maritime Ltd",
        "aliases": ["Horizon Maritime Logistics", "Horizon Bulk Carriers"],
        "list_name": "OFAC Non-SDN Menu-Based Sanctions",
        "program": "DPRK-EO13810",
        "country": "PA",
        "remarks": "Engaged in deceptive ship-to-ship maritime transfers in international waters.",
    },
]

PEP_DATABASE: List[Dict[str, Any]] = [
    {
        "id": "PEP-001",
        "entity_name": "Elena Rostova",
        "aliases": ["Elena Petrovna Rostova", "Elena V. Rostova"],
        "role": "Former Deputy Minister of Energy & Natural Resources",
        "country": "UA",
        "tenure": "2018 - 2023",
        "pep_tier": "Tier 1 (Senior Government Official)",
        "family_associates": ["Andrei Rostov (Spouse - Executive at State Oil Co)"],
        "status": "ACTIVE_PEP",
    },
    {
        "id": "PEP-002",
        "entity_name": "Carlos Mendoza Ramirez",
        "aliases": ["Carlos M. Ramirez", "Carlos Mendoza", "Carlos Ramirez"],
        "role": "Member of Parliament & Committee on Public Infrastructure",
        "country": "CO",
        "tenure": "2020 - Present",
        "pep_tier": "Tier 1 (National Politician)",
        "family_associates": ["Sofia Mendoza (Sister - Infrastructure Contractor)"],
        "status": "ACTIVE_PEP",
    },
    {
        "id": "PEP-003",
        "entity_name": "Marcus Sterling",
        "aliases": ["Sir Marcus Sterling", "Marcus E. Sterling"],
        "role": "Chairman of State Sovereign Wealth Advisory Board",
        "country": "GB",
        "tenure": "2019 - 2024",
        "pep_tier": "Tier 2 (Senior State Enterprise Official)",
        "family_associates": [],
        "status": "DOMESTIC_PEP",
    },
]

ADVERSE_MEDIA_DATABASE: List[Dict[str, Any]] = [
    {
        "id": "ADV-001",
        "entity_name": "Elena Rostova",
        "headline": "Special Prosecutor Opens Investigation into Ministry Energy Concession Contracts",
        "source": "Financial Transparency International / Eastern Herald",
        "date": "2023-04-14",
        "risk_category": "BRIBERY_CORRUPTION",
        "summary": "Parliamentary inquiry initiated into energy licensing awarded without public tender during tenure as Deputy Minister. Subject denies wrongdoing.",
    },
    {
        "id": "ADV-002",
        "entity_name": "Tariq Al-Mansoor",
        "headline": "Treasury Department Dismantles Multi-Jurisdiction Smuggling and Cash Courier Network",
        "source": "Global Financial Crimes Watch",
        "date": "2022-09-30",
        "risk_category": "MONEY_LAUNDERING_SANCTIONS_EVASION",
        "summary": "Targeted by multi-agency task force for moving tens of millions in structured wire transfers through offshore shell companies.",
    },
    {
        "id": "ADV-003",
        "entity_name": "Quantum Dynamics Technologies Ltd",
        "headline": "Tech Firm Faces Regulatory Scrutiny Over Unregistered Shareholder Transfers",
        "source": "Companies House Audit Bulletin",
        "date": "2024-01-10",
        "risk_category": "REGULATORY_COMPLIANCE",
        "summary": "Late filing of ultimate beneficial ownership register (PSC02) and conflicting registered offices submitted in annual confirmation.",
    },
    {
        "id": "ADV-004",
        "entity_name": "Atlas Trans-Oceanic Holdings SA",
        "headline": "Maritime Tribunal Concludes Commercial Cargo Demurrage Arbitration",
        "source": "Geneva Maritime Law Review",
        "date": "2025-06-18",
        "risk_category": "COMMERCIAL_DISPUTE",
        "summary": "Commercial charter demurrage arbitration resolved through mutual settlement. No criminal liability or regulatory sanctions imposed.",
    },
]

# Preset Demonstration Onboarding Cases (Micro SMBs, Small, Medium, Large, XL Enterprises, Individuals)
PRESET_DEMO_CASES = [
    # 1. Retail Individual - Clean Profile (Low Risk)
    {
        "case_number": "KYC-2026-0891",
        "entity_type": "INDIVIDUAL",
        "business_size": "MICRO_SMB",
        "primary_name": "Alexander James Wright",
        "email": "alex.wright@example.com",
        "phone": "+1 (555) 234-8901",
        "country_of_operation": "US",
        "trigger_type": "NEW_ONBOARDING",
        "priority": "LOW",
        "description": "Retail Onboarding - Clean profile, verified US passport and proof of address.",
        "documents": [
            {
                "filename": "passport_alexander_wright.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Alexander James Wright", "confidence": 0.99},
                    "first_name": {"value": "Alexander", "confidence": 0.99},
                    "last_name": {"value": "Wright", "confidence": 0.99},
                    "date_of_birth": {"value": "1988-06-14", "confidence": 0.98},
                    "gender": {"value": "M", "confidence": 0.99},
                    "nationality": {"value": "US", "confidence": 0.99},
                    "country_of_residence": {"value": "US", "confidence": 0.99},
                    "id_number": {"value": "548902134", "confidence": 0.99},
                    "issue_date": {"value": "2021-04-10", "confidence": 0.97},
                    "expiry_date": {"value": "2031-04-09", "confidence": 0.97},
                    "issuing_authority": {"value": "United States Department of State", "confidence": 0.98},
                    "mrz_code": {"value": "P<USAWRIGHT<<ALEXANDER<JAMES<<<<<<<<<<<<<<<5489021348USA8806144M3104097<<<<<<<<<<<<<<06", "confidence": 0.99},
                    "mrz_valid": True,
                    "is_expired": False,
                },
                "raw_text": "UNITED STATES OF AMERICA PASSPORT\nSurname: WRIGHT\nGiven Names: ALEXANDER JAMES\nNationality: UNITED STATES OF AMERICA\nDate of Birth: 14 JUN 1988\nSex: M\nPlace of Birth: CALIFORNIA, U.S.A.\nDate of Issue: 10 APR 2021\nDate of Expiration: 09 APR 2031\nPassport No: 548902134\nP<USAWRIGHT<<ALEXANDER<JAMES<<<<<<<<<<<<<<<\n5489021348USA8806144M3104097<<<<<<<<<<<<<<06",
                "validation_status": "VALID",
            },
            {
                "filename": "utility_bill_wright.pdf",
                "doc_type": "UTILITY_BILL",
                "extracted_data": {
                    "full_name": {"value": "Alexander J Wright", "confidence": 0.96},
                    "street_address": {"value": "742 Evergreen Terrace, Apt 4B", "confidence": 0.95},
                    "city": {"value": "Springfield", "confidence": 0.98},
                    "postal_code": {"value": "97477", "confidence": 0.97},
                    "country": {"value": "US", "confidence": 0.99},
                    "issue_date": {"value": "2026-08-15", "confidence": 0.95},
                    "is_expired": False,
                },
                "raw_text": "PACIFIC POWER & ELECTRIC BILL\nAccount: 9028-441-209\nCustomer Name: Alexander J Wright\nService Address: 742 Evergreen Terrace, Apt 4B, Springfield, OR 97477\nBilling Period: 15 JUL 2026 - 15 AUG 2026\nTotal Amount Due: $142.80",
                "validation_status": "VALID",
            },
        ],
    },
    # 2. Individual PEP & Adverse Media - High Risk
    {
        "case_number": "KYC-2026-0892",
        "entity_type": "INDIVIDUAL",
        "business_size": "MICRO_SMB",
        "primary_name": "Elena Rostova",
        "email": "e.rostova@consulting-partners.eu",
        "phone": "+44 20 7946 0912",
        "country_of_operation": "CY",
        "trigger_type": "EVENT_DRIVEN_REVIEW",
        "priority": "HIGH",
        "description": "PEP & Adverse Media Alert - Former Deputy Minister of Energy with active parliamentary investigation.",
        "documents": [
            {
                "filename": "passport_elena_rostova.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Elena Rostova", "confidence": 0.98},
                    "first_name": {"value": "Elena", "confidence": 0.98},
                    "last_name": {"value": "Rostova", "confidence": 0.98},
                    "date_of_birth": {"value": "1977-09-22", "confidence": 0.97},
                    "gender": {"value": "F", "confidence": 0.99},
                    "nationality": {"value": "UA", "confidence": 0.99},
                    "country_of_residence": {"value": "CY", "confidence": 0.94},
                    "id_number": {"value": "FB9928104", "confidence": 0.98},
                    "issue_date": {"value": "2020-02-15", "confidence": 0.95},
                    "expiry_date": {"value": "2030-02-14", "confidence": 0.95},
                    "mrz_code": {"value": "P<UKRROSTOVA<<ELENA<<<<<<<<<<<<<<<<<<<<<<<<FB99281048UKR7709226F3002144<<<<<<<<<<<<<<02", "confidence": 0.97},
                    "mrz_valid": True,
                    "is_expired": False,
                },
                "raw_text": "UKRAINE PASSPORT\nSurname: ROSTOVA\nGiven Names: ELENA\nDate of Birth: 22 SEP 1977\nSex: F\nNationality: UKRAINE\nPassport No: FB9928104\nDate of Expiry: 14 FEB 2030",
                "validation_status": "VALID",
            },
            {
                "filename": "bank_statement_cyprus.pdf",
                "doc_type": "BANK_STATEMENT",
                "extracted_data": {
                    "full_name": {"value": "Elena Petrovna Rostova", "confidence": 0.95},
                    "street_address": {"value": "12 Poseidonos Avenue, Tower 3, Suite 801", "confidence": 0.92},
                    "city": {"value": "Limassol", "confidence": 0.97},
                    "postal_code": {"value": "3042", "confidence": 0.95},
                    "country": {"value": "CY", "confidence": 0.98},
                    "issue_date": {"value": "2026-07-20", "confidence": 0.94},
                    "is_expired": False,
                },
                "raw_text": "BANK OF CYPRUS\nStatement of Account\nAccount Holder: Elena Petrovna Rostova\nAddress: 12 Poseidonos Avenue, Tower 3, Suite 801, Limassol 3042, Cyprus\nPeriod: 01 JUL 2026 - 20 JUL 2026",
                "validation_status": "VALID",
            },
        ],
    },
    # 3. Individual Sanctions Hit - Critical Block
    {
        "case_number": "KYC-2026-0893",
        "entity_type": "INDIVIDUAL",
        "business_size": "MICRO_SMB",
        "primary_name": "Tariq Al-Mansoor",
        "email": "t.mansoor@trade-network.org",
        "phone": "+971 4 391 0022",
        "country_of_operation": "SY",
        "trigger_type": "REGULATORY_TRIGGER",
        "priority": "URGENT",
        "description": "High-Risk Sanctions Match - Direct alias match on OFAC SDN and illicit finance network.",
        "documents": [
            {
                "filename": "id_card_tariq_mansoor.pdf",
                "doc_type": "NATIONAL_ID",
                "extracted_data": {
                    "full_name": {"value": "Tariq Al-Mansoor", "confidence": 0.95},
                    "first_name": {"value": "Tariq", "confidence": 0.95},
                    "last_name": {"value": "Al-Mansoor", "confidence": 0.95},
                    "date_of_birth": {"value": "1974-05-18", "confidence": 0.96},
                    "gender": {"value": "M", "confidence": 0.98},
                    "nationality": {"value": "SY", "confidence": 0.98},
                    "id_number": {"value": "SY-8491028-X", "confidence": 0.92},
                    "issue_date": {"value": "2019-01-10", "confidence": 0.90},
                    "expiry_date": {"value": "2024-01-09", "confidence": 0.90},
                    "is_expired": True,
                },
                "raw_text": "NATIONAL IDENTITY CARD\nName: Tariq Al-Mansoor\nDOB: 18 MAY 1974\nNationality: Syrian Arab Republic\nID: SY-8491028-X\nValidity: 10 JAN 2019 - 09 JAN 2024 (EXPIRED)",
                "validation_status": "EXPIRED",
            }
        ],
    },
    # 4. Micro SMB - Danish Artisanal Specialty Coffee & Roastery (Low Risk, Clean SDD)
    {
        "case_number": "KYC-2026-0895",
        "entity_type": "CORPORATE",
        "business_size": "MICRO_SMB",
        "primary_name": "Apex Nordic Roasters ApS",
        "email": "hello@apexnordicroasters.dk",
        "phone": "+45 31 92 84 00",
        "country_of_operation": "DK",
        "trigger_type": "NEW_ONBOARDING",
        "priority": "LOW",
        "description": "Micro SMB Onboarding - Danish specialty coffee roaster, single founder UBO (85%), clean SDD profile.",
        "documents": [
            {
                "filename": "danish_cvr_registration.pdf",
                "doc_type": "CERT_OF_INCORPORATION",
                "extracted_data": {
                    "company_name": {"value": "Apex Nordic Roasters ApS", "confidence": 0.99},
                    "registration_number": {"value": "DK-39281044", "confidence": 0.98},
                    "jurisdiction_of_incorporation": {"value": "DK", "confidence": 0.99},
                    "incorporation_date": {"value": "2023-05-10", "confidence": 0.97},
                    "street_address": {"value": "Jaegersborggade 42", "confidence": 0.96},
                    "city": {"value": "Copenhagen", "confidence": 0.98},
                    "postal_code": {"value": "2200", "confidence": 0.97},
                    "country": {"value": "DK", "confidence": 0.99},
                    "directors": ["Lars Moller"],
                    "ubos": [
                        {"name": "Lars Moller", "percentage": 85, "nationality": "DK", "pep": False},
                        {"name": "Freja Lind", "percentage": 15, "nationality": "DK", "pep": False},
                    ],
                },
                "raw_text": "ERHVERVSSTYRELSEN - CENTRAL BUSINESS REGISTER (CVR)\nCVR-nr: 39281044\nCompany Name: Apex Nordic Roasters ApS\nAddress: Jaegersborggade 42, 2200 Copenhagen N, Denmark\nManaging Director: Lars Moller\nOwnership: Lars Moller (85%), Freja Lind (15%)\nStatus: Active Commercial Enterprise",
                "validation_status": "VALID",
            },
            {
                "filename": "passport_lars_moller.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Lars Moller", "confidence": 0.98},
                    "date_of_birth": {"value": "1990-03-25", "confidence": 0.98},
                    "nationality": {"value": "DK", "confidence": 0.99},
                    "id_number": {"value": "DK-89210041", "confidence": 0.97},
                    "issue_date": {"value": "2022-01-15", "confidence": 0.96},
                    "expiry_date": {"value": "2032-01-14", "confidence": 0.96},
                    "is_expired": False,
                },
                "raw_text": "KINGDOM OF DENMARK PASSPORT\nName: MOLLER, LARS\nDOB: 25 MAR 1990\nNationality: DANISH\nPassport No: DK-89210041\nExpiry: 14 JAN 2032",
                "validation_status": "VALID",
            },
        ],
    },
    # 5. Small Business - Cross-Border Intermodal Logistics (Medium-High Risk, PEP Hit on UBO)
    {
        "case_number": "KYC-2026-0896",
        "entity_type": "CORPORATE",
        "business_size": "SMALL",
        "primary_name": "Veritas Logistics & Freight Solutions LLC",
        "email": "ops@veritasfreight.us",
        "phone": "+1 (305) 892-4411",
        "country_of_operation": "US",
        "trigger_type": "NEW_ONBOARDING",
        "priority": "HIGH",
        "description": "Small Corporate Logistics - Cross-border intermodal freight routes to LATAM; 49% UBO is active PEP.",
        "documents": [
            {
                "filename": "delaware_formation_certificate.pdf",
                "doc_type": "CERT_OF_INCORPORATION",
                "extracted_data": {
                    "company_name": {"value": "Veritas Logistics & Freight Solutions LLC", "confidence": 0.99},
                    "registration_number": {"value": "DE-7849102", "confidence": 0.98},
                    "jurisdiction_of_incorporation": {"value": "US", "confidence": 0.99},
                    "incorporation_date": {"value": "2021-09-01", "confidence": 0.97},
                    "street_address": {"value": "1201 North Market Street, Suite 400", "confidence": 0.95},
                    "city": {"value": "Wilmington", "confidence": 0.98},
                    "postal_code": {"value": "19801", "confidence": 0.97},
                    "country": {"value": "US", "confidence": 0.99},
                    "directors": ["Mateo Hernandez", "Carlos Mendoza Ramirez"],
                    "ubos": [
                        {"name": "Mateo Hernandez", "percentage": 51, "nationality": "US", "pep": False},
                        {"name": "Carlos Mendoza Ramirez", "percentage": 49, "nationality": "CO", "pep": True},
                    ],
                },
                "raw_text": "STATE OF DELAWARE - CERTIFICATE OF FORMATION\nEntity File Number: 7849102\nEntity Name: Veritas Logistics & Freight Solutions LLC\nFormation Date: September 1, 2021\nPrincipal Office: 1201 North Market Street, Suite 400, Wilmington, DE 19801\nMembers / Managing Directors: Mateo Hernandez (51%), Carlos Mendoza Ramirez (49%)",
                "validation_status": "VALID",
            },
            {
                "filename": "passport_mateo_hernandez.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Mateo Hernandez", "confidence": 0.98},
                    "date_of_birth": {"value": "1982-12-11", "confidence": 0.98},
                    "nationality": {"value": "US", "confidence": 0.99},
                    "id_number": {"value": "USA-9028441", "confidence": 0.97},
                    "issue_date": {"value": "2020-04-18", "confidence": 0.95},
                    "expiry_date": {"value": "2030-04-17", "confidence": 0.95},
                    "is_expired": False,
                },
                "raw_text": "UNITED STATES OF AMERICA PASSPORT\nName: HERNANDEZ, MATEO\nDOB: 11 DEC 1982\nNationality: USA\nPassport No: USA-9028441\nExpiry: 17 APR 2030",
                "validation_status": "VALID",
            },
        ],
    },
    # 6. Medium Business - Tech & Corporate Software (Medium Risk, Regulatory Warning)
    {
        "case_number": "KYC-2026-0894",
        "entity_type": "CORPORATE",
        "business_size": "MEDIUM",
        "primary_name": "Quantum Dynamics Technologies Ltd",
        "email": "compliance@quantumdynamics.tech",
        "phone": "+44 20 8123 4567",
        "country_of_operation": "GB",
        "trigger_type": "PERIODIC_RE_KYC",
        "priority": "MEDIUM",
        "description": "Medium Tech Corporate - Multi-director structure with UBO verification and Companies House filing query.",
        "documents": [
            {
                "filename": "certificate_of_incorporation.pdf",
                "doc_type": "CERT_OF_INCORPORATION",
                "extracted_data": {
                    "company_name": {"value": "Quantum Dynamics Technologies Ltd", "confidence": 0.99},
                    "registration_number": {"value": "13948201", "confidence": 0.98},
                    "jurisdiction_of_incorporation": {"value": "GB", "confidence": 0.99},
                    "incorporation_date": {"value": "2022-03-15", "confidence": 0.97},
                    "street_address": {"value": "25 Bank Street, Canary Wharf", "confidence": 0.95},
                    "city": {"value": "London", "confidence": 0.98},
                    "postal_code": {"value": "E14 5JP", "confidence": 0.97},
                    "country": {"value": "GB", "confidence": 0.99},
                    "directors": ["Marcus Vance", "Sarah Jenkins"],
                    "ubos": [
                        {"name": "Marcus Vance", "percentage": 65, "nationality": "GB", "pep": False},
                        {"name": "Sarah Jenkins", "percentage": 35, "nationality": "GB", "pep": False},
                    ],
                },
                "raw_text": "COMPANIES HOUSE - CERTIFICATE OF INCORPORATION\nCompany No: 13948201\nCompany Name: Quantum Dynamics Technologies Ltd\nIncorporation Date: 15 March 2022\nRegistered Office: 25 Bank Street, Canary Wharf, London, E14 5JP, United Kingdom\nDirectors: Marcus Vance, Sarah Jenkins\nShare Capital: 100,000 GBP (Marcus Vance 65%, Sarah Jenkins 35%)",
                "validation_status": "VALID",
            },
            {
                "filename": "ubo_passport_marcus_vance.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Marcus Vance", "confidence": 0.98},
                    "date_of_birth": {"value": "1983-11-05", "confidence": 0.98},
                    "nationality": {"value": "GB", "confidence": 0.99},
                    "id_number": {"value": "GB-9028114", "confidence": 0.97},
                    "issue_date": {"value": "2021-08-01", "confidence": 0.96},
                    "expiry_date": {"value": "2031-07-31", "confidence": 0.96},
                    "is_expired": False,
                },
                "raw_text": "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND PASSPORT\nName: VANCE, MARCUS\nDOB: 05 NOV 1983\nNationality: BRITISH CITIZEN\nPassport No: GB-9028114\nExpiry: 31 JUL 2031",
                "validation_status": "VALID",
            },
        ],
    },
    # 7. Medium Business - FinTech Payments & FX Remittance (Medium-High Risk, High Velocity Wires & PEP Director)
    {
        "case_number": "KYC-2026-0897",
        "entity_type": "CORPORATE",
        "business_size": "MEDIUM",
        "primary_name": "Nexus Pay Global Pte Ltd",
        "email": "compliance@nexuspayglobal.sg",
        "phone": "+65 6820 9100",
        "country_of_operation": "SG",
        "trigger_type": "NEW_ONBOARDING",
        "priority": "HIGH",
        "description": "Medium FinTech Enterprise - Cross-border B2B digital payment gateway; Board Chairman is Domestic PEP.",
        "documents": [
            {
                "filename": "acra_singapore_profile.pdf",
                "doc_type": "CERT_OF_INCORPORATION",
                "extracted_data": {
                    "company_name": {"value": "Nexus Pay Global Pte Ltd", "confidence": 0.99},
                    "registration_number": {"value": "202108941G", "confidence": 0.98},
                    "jurisdiction_of_incorporation": {"value": "SG", "confidence": 0.99},
                    "incorporation_date": {"value": "2021-06-18", "confidence": 0.97},
                    "street_address": {"value": "10 Marina Boulevard, Marina Bay Financial Centre Tower 2", "confidence": 0.96},
                    "city": {"value": "Singapore", "confidence": 0.99},
                    "postal_code": {"value": "018983", "confidence": 0.98},
                    "country": {"value": "SG", "confidence": 0.99},
                    "directors": ["Wei Zhang", "Marcus Sterling"],
                    "ubos": [
                        {"name": "Wei Zhang", "percentage": 42, "nationality": "SG", "pep": False},
                        {"name": "Marcus Sterling", "percentage": 58, "nationality": "GB", "pep": True},
                    ],
                },
                "raw_text": "ACCOUNTING AND CORPORATE REGULATORY AUTHORITY (ACRA) SINGAPORE\nUEN: 202108941G\nCompany Name: Nexus Pay Global Pte Ltd\nIncorporation Date: 18 June 2021\nRegistered Address: 10 Marina Boulevard, #28-01 MBFC Tower 2, Singapore 018983\nPaid Up Capital: SGD 2,500,000\nDirectors: Wei Zhang (Chief Executive), Sir Marcus Sterling (Non-Executive Chairman)",
                "validation_status": "VALID",
            },
            {
                "filename": "passport_wei_zhang.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Wei Zhang", "confidence": 0.98},
                    "date_of_birth": {"value": "1986-08-19", "confidence": 0.98},
                    "nationality": {"value": "SG", "confidence": 0.99},
                    "id_number": {"value": "E9824102A", "confidence": 0.98},
                    "issue_date": {"value": "2022-03-01", "confidence": 0.97},
                    "expiry_date": {"value": "2032-02-28", "confidence": 0.97},
                    "is_expired": False,
                },
                "raw_text": "REPUBLIC OF SINGAPORE PASSPORT\nName: ZHANG, WEI\nDOB: 19 AUG 1986\nNationality: SINGAPORE CITIZEN\nPassport No: E9824102A\nExpiry: 28 FEB 2032",
                "validation_status": "VALID",
            },
        ],
    },
    # 8. Large Business - Precision Heavy Machinery & Industrial Engineering (Low-Medium Risk, Group Structure)
    {
        "case_number": "KYC-2026-0898",
        "entity_type": "CORPORATE",
        "business_size": "LARGE",
        "primary_name": "Aethelgard Heavy Industries AG",
        "email": "corporate.compliance@aethelgard-ag.de",
        "phone": "+49 89 9283 00",
        "country_of_operation": "DE",
        "trigger_type": "PERIODIC_RE_KYC",
        "priority": "MEDIUM",
        "description": "Large Industrial Corporate - Munich precision engineering conglomerate with dual-use export screening.",
        "documents": [
            {
                "filename": "handelsregister_excerpt_munich.pdf",
                "doc_type": "CERT_OF_INCORPORATION",
                "extracted_data": {
                    "company_name": {"value": "Aethelgard Heavy Industries AG", "confidence": 0.99},
                    "registration_number": {"value": "HRB 294812", "confidence": 0.98},
                    "jurisdiction_of_incorporation": {"value": "DE", "confidence": 0.99},
                    "incorporation_date": {"value": "2015-11-20", "confidence": 0.97},
                    "street_address": {"value": "Industriestrasse 88", "confidence": 0.96},
                    "city": {"value": "Munich", "confidence": 0.98},
                    "postal_code": {"value": "80339", "confidence": 0.97},
                    "country": {"value": "DE", "confidence": 0.99},
                    "directors": ["Dr. Klaus von Aethelgard", "Helena Becker"],
                    "ubos": [
                        {"name": "Dr. Klaus von Aethelgard", "percentage": 58, "nationality": "DE", "pep": False},
                        {"name": "Helena Becker", "percentage": 42, "nationality": "DE", "pep": False},
                    ],
                },
                "raw_text": "AMTSGERICHT MUNCHEN - HANDELSREGISTER ABTEILUNG B (HRB 294812)\nFirma: Aethelgard Heavy Industries AG\nSitz: Industriestrasse 88, 80339 Munchen, Deutschland\nGrundkapital: EUR 50,000,000\nVorstand: Dr. Klaus von Aethelgard (Vorsitzender), Helena Becker (Finanzvorstand)\nGegenstand: Herstellung von Prazisionsturbinen und Industrieanlagen.",
                "validation_status": "VALID",
            },
            {
                "filename": "personalausweis_klaus_aethelgard.pdf",
                "doc_type": "NATIONAL_ID",
                "extracted_data": {
                    "full_name": {"value": "Dr. Klaus von Aethelgard", "confidence": 0.98},
                    "date_of_birth": {"value": "1964-07-08", "confidence": 0.98},
                    "nationality": {"value": "DE", "confidence": 0.99},
                    "id_number": {"value": "T22000129", "confidence": 0.98},
                    "issue_date": {"value": "2020-05-12", "confidence": 0.96},
                    "expiry_date": {"value": "2030-05-11", "confidence": 0.96},
                    "is_expired": False,
                },
                "raw_text": "BUNDESREPUBLIK DEUTSCHLAND PERSONALAUSWEIS\nName: VON AETHELGARD\nVorname: KLAUS\nGeburtstag: 08 JUL 1964\nStaatsangehoerigkeit: DEUTSCH\nAusweisnummer: T22000129\nGueltig bis: 11 MAI 2030",
                "validation_status": "VALID",
            },
        ],
    },
    # 9. XL Multinational Enterprise - Energy Commodities, Maritime Fleet & Infrastructure (High Risk, Global SPV)
    {
        "case_number": "KYC-2026-0899",
        "entity_type": "CORPORATE",
        "business_size": "XL_ENTERPRISE",
        "primary_name": "Atlas Trans-Oceanic Holdings SA",
        "email": "group.governance@atlastransoceanic.com",
        "phone": "+971 4 455 8800",
        "country_of_operation": "AE",
        "trigger_type": "EVENT_DRIVEN_REVIEW",
        "priority": "URGENT",
        "description": "XL Multinational Conglomerate - Global energy commodities trading and charter fleet leasing across DIFC, Geneva, and London; high wire turnover requiring senior MLRO sign-off.",
        "documents": [
            {
                "filename": "difc_commercial_license_atlas.pdf",
                "doc_type": "CERT_OF_INCORPORATION",
                "extracted_data": {
                    "company_name": {"value": "Atlas Trans-Oceanic Holdings SA", "confidence": 0.99},
                    "registration_number": {"value": "DIFC-CL-4890", "confidence": 0.98},
                    "jurisdiction_of_incorporation": {"value": "AE", "confidence": 0.99},
                    "incorporation_date": {"value": "2018-02-28", "confidence": 0.97},
                    "street_address": {"value": "Gate Precinct 4, Level 7, DIFC", "confidence": 0.96},
                    "city": {"value": "Dubai", "confidence": 0.99},
                    "postal_code": {"value": "506500", "confidence": 0.97},
                    "country": {"value": "AE", "confidence": 0.99},
                    "directors": ["Alistair Finch-Hatton", "Tariq Mansoor Al-Sabah"],
                    "ubos": [
                        {"name": "Alistair Finch-Hatton", "percentage": 52, "nationality": "GB", "pep": False},
                        {"name": "Tariq Mansoor Al-Sabah", "percentage": 48, "nationality": "AE", "pep": False},
                    ],
                },
                "raw_text": "DUBAI INTERNATIONAL FINANCIAL CENTRE (DIFC) COMMERCIAL LICENSE\nLicense No: DIFC-CL-4890\nLegal Entity: Atlas Trans-Oceanic Holdings SA\nOperating Headquarters: Gate Precinct 4, Level 7, DIFC, Dubai, United Arab Emirates\nAuthorized Capital: USD 250,000,000\nBoard of Governors: Alistair Finch-Hatton (Managing Director), Tariq Mansoor Al-Sabah (Executive Governor)\nBusiness Activities: Global Energy Commodities & Maritime Fleet Asset Management",
                "validation_status": "VALID",
            },
            {
                "filename": "passport_alistair_finch_hatton.pdf",
                "doc_type": "PASSPORT",
                "extracted_data": {
                    "full_name": {"value": "Alistair Finch-Hatton", "confidence": 0.98},
                    "date_of_birth": {"value": "1972-10-14", "confidence": 0.98},
                    "nationality": {"value": "GB", "confidence": 0.99},
                    "id_number": {"value": "GB-7749102", "confidence": 0.97},
                    "issue_date": {"value": "2021-06-20", "confidence": 0.96},
                    "expiry_date": {"value": "2031-06-19", "confidence": 0.96},
                    "is_expired": False,
                },
                "raw_text": "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND PASSPORT\nName: FINCH-HATTON, ALISTAIR\nDOB: 14 OCT 1972\nNationality: BRITISH CITIZEN\nPassport No: GB-7749102\nExpiry: 19 JUN 2031",
                "validation_status": "VALID",
            },
        ],
    },
]
